/**
 * Migration script to import all static data to Sanity CMS
 * 
 * Usage:
 * 1. Set up your Sanity project and get your project ID and dataset
 * 2. Create a .env.local file with:
 *    NEXT_PUBLIC_SANITY_PROJECT_ID=your-project-id
 *    NEXT_PUBLIC_SANITY_DATASET=production
 *    SANITY_API_WRITE_TOKEN=your-write-token
 * 3. Run: npm run migrate
 */

import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'
import { join } from 'path'

// Load environment variables
dotenv.config({ path: join(process.cwd(), '.env.local') })

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || ''
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'
const token = process.env.SANITY_API_WRITE_TOKEN || ''

if (!projectId || !token) {
  console.error('Error: NEXT_PUBLIC_SANITY_PROJECT_ID and SANITY_API_WRITE_TOKEN must be set in .env.local')
  process.exit(1)
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: '2024-01-01',
  useCdn: true,
  token,
})

// Site Settings
const siteSettings = {
  _type: 'siteSettings',
  title: 'Ganegoda International',
  description: 'Premium luxury car dealership',
  phone: '+1 (234) 567-890',
  whatsapp: '1234567890',
  email: 'info@ganegoda.com',
  address: 'Your business address here',
}

// Hero Section Settings (single document)
const heroSection = {
  _type: 'heroSection',
  label: 'Premium Automotive Experience',
  mainTitle: 'Premium Cars.\nTrusted Deals.\nElite Experience.',
  subtitle: 'Discover our exclusive collection of luxury vehicles. Every car curated for excellence, every deal crafted for trust.',
}

// Hero Images (multiple images for slider)
const heroImages = [
  {
    _type: 'heroImage',
    order: 0,
    alt: 'Luxury car showcase',
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-hero-1', // You'll need to upload images first
      },
    },
  },
  {
    _type: 'heroImage',
    order: 1,
    alt: 'Premium vehicle collection',
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-hero-2',
      },
    },
  },
  // Add more hero images as needed
]

// Vehicles
// Note: For new vehicles, ID and slug will be auto-generated by the schema
// These manual IDs are only for migration of existing data
const vehicles = [
  {
    _type: 'vehicle',
    id: 'f1', // Auto-generated for new vehicles
    name: 'BMW 520d',
    slug: { _type: 'slug', current: 'bmw-520d' },
    price: 12500000,
    brand: 'BMW',
    model: '520d',
    year: 2020,
    mileage: 35000,
    engine: '2.0L Turbo Diesel I4',
    fuel: 'Diesel',
    transmission: 'Auto',
    driveType: 'RWD',
    condition: 'used',
    color: 'Mineral Grey Metallic',
    status: 'used',
    description: `Experience luxury and performance in this exceptional BMW 520d. This premium sedan combines elegant design with impressive fuel efficiency and powerful performance.

The 2.0-liter turbocharged diesel engine delivers excellent torque and fuel economy, making it perfect for both city driving and long journeys. The 8-speed automatic transmission ensures smooth gear changes, while the rear-wheel-drive system provides a dynamic driving experience.

Inside, you'll find a sophisticated interior featuring premium leather upholstery, heated seats, BMW's iDrive infotainment system with a large touchscreen display, and advanced driver assistance systems. The spacious cabin offers exceptional comfort for all passengers.

This vehicle has been meticulously maintained and comes with a comprehensive service history. It represents an excellent opportunity to own a premium German sedan that combines luxury, performance, and efficiency.`,
    features: [
      'BMW iDrive Infotainment System',
      'Navigation System',
      'Leather Upholstery',
      'Heated Front Seats',
      'Parking Sensors',
      'Rear View Camera',
      'LED Headlights',
      'Cruise Control',
      'Bluetooth Connectivity',
      'USB Ports',
      'Climate Control',
      'Keyless Entry',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-bmw520-main',
      },
    },
    images: [],
    featured: true,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'f2',
    name: 'BMW X1',
    slug: { _type: 'slug', current: 'bmw-x1' },
    price: 11500000,
    brand: 'BMW',
    model: 'X1',
    year: 2019,
    mileage: 42000,
    engine: '2.0L Turbo Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Alpine White',
    status: 'used',
    description: `Discover the perfect blend of versatility and luxury in this BMW X1. This compact SUV offers exceptional practicality without compromising on style or performance.

The 2.0-liter turbocharged petrol engine provides responsive acceleration and smooth power delivery. The 8-speed automatic transmission ensures seamless gear changes, while the front-wheel-drive system offers excellent traction and fuel efficiency.

The interior features premium materials, comfortable seating for five, and BMW's latest infotainment system with smartphone integration. The flexible cargo space makes it perfect for daily commutes and weekend adventures alike.

This well-maintained vehicle comes with a complete service history and represents an excellent value in the premium compact SUV segment.`,
    features: [
      'BMW iDrive System',
      'Apple CarPlay & Android Auto',
      'Panoramic Sunroof',
      'Leather Seats',
      'Parking Assistant',
      'Rear View Camera',
      'LED Daytime Running Lights',
      'Cruise Control',
      'Bluetooth Audio',
      'USB Charging Ports',
      'Dual Zone Climate Control',
      'Keyless Start',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-bmwx1-main',
      },
    },
    images: [],
    featured: true,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'f3',
    name: 'Honda Civic Blue',
    slug: { _type: 'slug', current: 'honda-civic-blue' },
    price: 8500000,
    brand: 'Honda',
    model: 'Civic',
    year: 2021,
    mileage: 28000,
    engine: '1.5L Turbo Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Aegean Blue Metallic',
    status: 'used',
    description: `Experience the perfect combination of style, performance, and reliability in this stunning Honda Civic. This sporty sedan delivers an engaging driving experience with excellent fuel economy.

The 1.5-liter turbocharged petrol engine provides impressive power and torque, making every drive exciting. The CVT automatic transmission ensures smooth acceleration and optimal fuel efficiency. The front-wheel-drive system offers excellent handling and stability.

Inside, you'll find a modern interior with comfortable seating, Honda's intuitive infotainment system, and advanced safety features. The spacious cabin and generous trunk space make it perfect for families and daily use.

This well-maintained vehicle comes with a complete service history and represents excellent value in the compact sedan segment.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '7-inch Touchscreen Display',
      'Honda LaneWatch',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'Road Departure Mitigation',
      'LED Headlights',
      'Push Button Start',
      'Remote Engine Start',
      'Dual Zone Climate Control',
      'Heated Front Seats',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-civic-blue-main',
      },
    },
    images: [],
    featured: true,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'f4',
    name: 'Honda Vezel',
    slug: { _type: 'slug', current: 'honda-vezel' },
    price: 10500000,
    brand: 'Honda',
    model: 'Vezel',
    year: 2020,
    mileage: 38000,
    engine: '1.5L Hybrid I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Platinum White Pearl',
    status: 'used',
    description: `Discover exceptional fuel efficiency and versatility in this Honda Vezel hybrid. This compact SUV combines the best of both worlds with its efficient hybrid powertrain and practical design.

The 1.5-liter hybrid engine delivers excellent fuel economy while providing smooth and responsive performance. The e-CVT transmission ensures seamless power delivery, and the front-wheel-drive system offers excellent traction and efficiency.

The interior features modern design with comfortable seating, Honda's infotainment system, and advanced safety technologies. The flexible cargo space and versatile seating make it perfect for urban driving and weekend getaways.

This well-maintained hybrid vehicle comes with a complete service history and represents an excellent choice for eco-conscious drivers seeking reliability and efficiency.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '7-inch Display Audio',
      'Honda LaneWatch',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'Lane Keeping Assist',
      'LED Headlights',
      'Push Button Start',
      'Smart Entry System',
      'Climate Control',
      'Rear View Camera',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-vezel-main',
      },
    },
    images: [],
    featured: true,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'p1',
    name: 'Honda Civic',
    slug: { _type: 'slug', current: 'honda-civic' },
    price: 8500000,
    brand: 'Honda',
    model: 'Civic',
    year: 2021,
    mileage: 25000,
    engine: '1.5L Turbo Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Rallye Red',
    status: 'used',
    description: `Experience the perfect combination of style, performance, and reliability in this stunning Honda Civic. This sporty sedan delivers an engaging driving experience with excellent fuel economy.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '7-inch Touchscreen Display',
      'Honda LaneWatch',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'Road Departure Mitigation',
      'LED Headlights',
      'Push Button Start',
      'Remote Engine Start',
      'Dual Zone Climate Control',
      'Heated Front Seats',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-civic1-main',
      },
    },
    images: [],
    featured: false,
    popular: true,
  },
  {
    _type: 'vehicle',
    id: 'p2',
    name: 'Honda City',
    slug: { _type: 'slug', current: 'honda-city' },
    price: 7500000,
    brand: 'Honda',
    model: 'City',
    year: 2020,
    mileage: 32000,
    engine: '1.5L Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Platinum White Pearl',
    status: 'used',
    description: `Discover exceptional value and reliability in this Honda City. This compact sedan offers excellent fuel economy, comfortable ride, and modern features at an affordable price point.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '8-inch Touchscreen',
      'Rear View Camera',
      'Lane Watch Camera',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'LED Headlights',
      'Push Button Start',
      'Smart Entry System',
      'Climate Control',
      'USB Ports',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-hondacity-main',
      },
    },
    images: [],
    featured: false,
    popular: true,
  },
  {
    _type: 'vehicle',
    id: 'p3',
    name: 'Suzuki Swift',
    slug: { _type: 'slug', current: 'suzuki-swift' },
    price: 5500000,
    brand: 'Suzuki',
    model: 'Swift',
    year: 2019,
    mileage: 45000,
    engine: '1.2L Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Pearl Metallic White',
    status: 'used',
    description: `Experience fun and efficient driving in this Suzuki Swift. This compact hatchback offers excellent fuel economy, nimble handling, and modern features in a stylish package.`,
    features: [
      'Apple CarPlay & Android Auto',
      '7-inch Touchscreen Display',
      'Rear View Camera',
      'Keyless Entry',
      'Push Button Start',
      'Bluetooth Connectivity',
      'USB Ports',
      'Climate Control',
      'Power Windows',
      'Power Steering',
      'ABS Brakes',
      'Dual Airbags',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-swift-main',
      },
    },
    images: [],
    featured: false,
    popular: true,
  },
  {
    _type: 'vehicle',
    id: 'p4',
    name: 'Honda Civic Blue',
    slug: { _type: 'slug', current: 'honda-civic-blue-2' },
    price: 8500000,
    brand: 'Honda',
    model: 'Civic',
    year: 2021,
    mileage: 28000,
    engine: '1.5L Turbo Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Aegean Blue Metallic',
    status: 'used',
    description: `Experience the perfect combination of style, performance, and reliability in this stunning Honda Civic.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '7-inch Touchscreen Display',
      'Honda LaneWatch',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'Road Departure Mitigation',
      'LED Headlights',
      'Push Button Start',
      'Remote Engine Start',
      'Dual Zone Climate Control',
      'Heated Front Seats',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-civic-blue-main',
      },
    },
    images: [],
    featured: false,
    popular: true,
  },
  {
    _type: 'vehicle',
    id: 'r1',
    name: 'BMW 520d',
    slug: { _type: 'slug', current: 'bmw-520d-reserved' },
    price: 12500000,
    brand: 'BMW',
    model: '520d',
    year: 2020,
    mileage: 35000,
    engine: '2.0L Turbo Diesel I4',
    fuel: 'Diesel',
    transmission: 'Auto',
    driveType: 'RWD',
    condition: 'used',
    color: 'Mineral Grey Metallic',
    status: 'reserved',
    description: `Experience luxury and performance in this exceptional BMW 520d. This premium sedan combines elegant design with impressive fuel efficiency and powerful performance.`,
    features: [
      'BMW iDrive Infotainment System',
      'Navigation System',
      'Leather Upholstery',
      'Heated Front Seats',
      'Parking Sensors',
      'Rear View Camera',
      'LED Headlights',
      'Cruise Control',
      'Bluetooth Connectivity',
      'USB Ports',
      'Climate Control',
      'Keyless Entry',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-bmw520-main',
      },
    },
    images: [],
    featured: false,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'r2',
    name: 'BMW X1',
    slug: { _type: 'slug', current: 'bmw-x1-reserved' },
    price: 11500000,
    brand: 'BMW',
    model: 'X1',
    year: 2019,
    mileage: 42000,
    engine: '2.0L Turbo Petrol I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Alpine White',
    status: 'reserved',
    description: `Discover the perfect blend of versatility and luxury in this BMW X1.`,
    features: [
      'BMW iDrive System',
      'Apple CarPlay & Android Auto',
      'Panoramic Sunroof',
      'Leather Seats',
      'Parking Assistant',
      'Rear View Camera',
      'LED Daytime Running Lights',
      'Cruise Control',
      'Bluetooth Audio',
      'USB Charging Ports',
      'Dual Zone Climate Control',
      'Keyless Start',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-bmwx1-main',
      },
    },
    images: [],
    featured: false,
    popular: false,
  },
  {
    _type: 'vehicle',
    id: 'r3',
    name: 'Honda Vezel',
    slug: { _type: 'slug', current: 'honda-vezel-reserved' },
    price: 10500000,
    brand: 'Honda',
    model: 'Vezel',
    year: 2020,
    mileage: 38000,
    engine: '1.5L Hybrid I4',
    fuel: 'Petrol',
    transmission: 'Auto',
    driveType: 'FWD',
    condition: 'used',
    color: 'Platinum White Pearl',
    status: 'reserved',
    description: `Discover exceptional fuel efficiency and versatility in this Honda Vezel hybrid.`,
    features: [
      'Honda Sensing Safety Suite',
      'Apple CarPlay & Android Auto',
      '7-inch Display Audio',
      'Honda LaneWatch',
      'Adaptive Cruise Control',
      'Collision Mitigation Braking',
      'Lane Keeping Assist',
      'LED Headlights',
      'Push Button Start',
      'Smart Entry System',
      'Climate Control',
      'Rear View Camera',
    ],
    mainImage: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-vezel-main',
      },
    },
    images: [],
    featured: false,
    popular: false,
  },
]

// Testimonials
const testimonials = [
  {
    _type: 'testimonial',
    name: 'James Mitchell',
    message:
      "Ganegoda International exceeded all my expectations. The team's professionalism and attention to detail made purchasing my dream car an absolute pleasure. Highly recommended!",
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-testimonial-1',
      },
    },
    order: 0,
  },
  {
    _type: 'testimonial',
    name: 'Sarah Williams',
    message:
      "Impeccable service from start to finish. They sourced the exact specification I wanted and handled everything seamlessly. A truly premium experience.",
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-testimonial-2',
      },
    },
    order: 1,
  },
  {
    _type: 'testimonial',
    name: 'Michael Chen',
    message:
      "The transparency and trustworthiness I experienced here is unmatched. They've earned a customer for life. My third purchase and still outstanding.",
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-testimonial-3',
      },
    },
    order: 2,
  },
]

// FAQs
const faqs = [
  {
    _type: 'faq',
    question: 'How does the vehicle buying process work?',
    answer:
      "Our buying process is simple and transparent. Browse our inventory online, schedule a viewing, and our team will guide you through financing options and paperwork. We handle everything from inspection to delivery.",
    order: 0,
  },
  {
    _type: 'faq',
    question: 'Do you offer financing options?',
    answer:
      "Yes, we partner with leading financial institutions to offer competitive financing rates. Our finance team will work with you to find the best terms based on your situation.",
    order: 1,
  },
  {
    _type: 'faq',
    question: 'Can I trade in my current vehicle?',
    answer:
      "Absolutely! We accept trade-ins of all makes and models. Bring your vehicle for a free evaluation, and we'll provide a competitive offer that can be applied to your new purchase.",
    order: 2,
  },
  {
    _type: 'faq',
    question: 'What warranty do you offer?',
    answer:
      "All our vehicles come with a comprehensive warranty. New vehicles include manufacturer warranty, while pre-owned vehicles come with our exclusive Ganegoda International warranty covering major components.",
    order: 3,
  },
  {
    _type: 'faq',
    question: 'How can I pre-order an upcoming vehicle?',
    answer:
      "Visit our Pre-Orders page to see upcoming vehicles. Select your desired model, pay a refundable deposit, and we'll keep you updated on availability and delivery timeline.",
    order: 4,
  },
  {
    _type: 'faq',
    question: 'Do you ship vehicles internationally?',
    answer:
      "Yes, we offer worldwide shipping. Our logistics team handles all documentation, customs clearance, and delivery to your location. Contact us for a shipping quote.",
    order: 5,
  },
  {
    _type: 'faq',
    question: 'What documents do I need to purchase a vehicle?',
    answer:
      "You'll need a valid ID, proof of residence, and proof of income for financing. For cash purchases, only valid ID and proof of residence are required.",
    order: 6,
  },
  {
    _type: 'faq',
    question: 'Can I return a vehicle after purchase?',
    answer:
      "We offer a 7-day satisfaction guarantee. If you're not completely satisfied, return the vehicle in its original condition for a full refund, subject to our terms and conditions.",
    order: 7,
  },
]

// Pre-Orders
const preOrders = [
  {
    _type: 'preOrder',
    id: 'po1',
    name: 'Porsche 911 GT3 RS',
    slug: { _type: 'slug', current: 'porsche-911-gt3-rs' },
    expectedPrice: 'From LKR 67,500,000',
    expectedArrival: 'Q2 2025',
    slotsAvailable: 3,
    specifications: ['4.0L Flat-6', '525 HP', 'Track-focused suspension'],
    deliveryDuration: {
      title: 'Delivery Duration',
      body: '8-12 weeks from order confirmation. Delivery time may vary based on customization options and shipping location.',
      items: [
        'Standard delivery: 8-10 weeks',
        'Custom orders: 10-12 weeks',
        'Express delivery available (additional charges apply)',
      ],
    },
    warrantyCoverage: {
      title: 'Warranty Coverage',
      body: '2 years or 50,000 km (whichever comes first). Comprehensive warranty covering all manufacturing defects.',
      items: [
        'Engine and transmission',
        'Electrical systems',
        'Air conditioning',
        'Manufacturing defects',
        'Roadside assistance',
        'Free service for first 10,000 km',
      ],
    },
    personalLCImport: {
      title: 'Personal LC Import',
      body: 'Personal Letter of Credit (LC) allows individuals to import vehicles for personal use with simplified documentation.',
      items: [
        'Simplified import process for personal use',
        'Lower documentation requirements',
        'Faster processing time (2-3 weeks)',
        'Direct ownership transfer',
        'Suitable for first-time importers',
      ],
    },
    nonPersonalLCImport: {
      title: 'Non-Personal LC Import',
      body: 'Non-Personal LC is ideal for businesses, companies, or commercial vehicle imports with comprehensive documentation.',
      items: [
        'Suitable for commercial/business use',
        'Tax benefits for registered businesses',
        'Bulk import options available',
        'Corporate financing options',
        'Dedicated account manager support',
      ],
    },
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-preorder-1',
      },
    },
  },
  {
    _type: 'preOrder',
    id: 'po2',
    name: 'BMW XM Label Red',
    slug: { _type: 'slug', current: 'bmw-xm-label-red' },
    expectedPrice: 'From LKR 55,500,000',
    expectedArrival: 'Q1 2025',
    slotsAvailable: 5,
    specifications: ['Hybrid V8', '738 HP', 'M Carbon exterior'],
    deliveryDuration: {
      title: 'Delivery Duration',
      body: '6-10 weeks from order confirmation.',
      items: [
        'Standard delivery: 6-8 weeks',
        'Custom orders: 8-10 weeks',
      ],
    },
    warrantyCoverage: {
      title: 'Warranty Coverage',
      body: '3 years unlimited mileage',
      items: [
        'Engine and transmission',
        'Hybrid system',
        'Electrical systems',
        'Carbon fiber components',
        'Manufacturing defects',
        '24/7 concierge service',
      ],
    },
    personalLCImport: {
      title: 'Personal LC Import',
      body: 'Personal Letter of Credit (LC) allows individuals to import vehicles for personal use with simplified documentation.',
      items: [
        'Simplified import process for personal use',
        'Lower documentation requirements',
        'Faster processing time (2-3 weeks)',
        'Direct ownership transfer',
        'Suitable for first-time importers',
      ],
    },
    nonPersonalLCImport: {
      title: 'Non-Personal LC Import',
      body: 'Non-Personal LC is ideal for businesses, companies, or commercial vehicle imports with comprehensive documentation.',
      items: [
        'Suitable for commercial/business use',
        'Tax benefits for registered businesses',
        'Bulk import options available',
        'Corporate financing options',
        'Dedicated account manager support',
      ],
    },
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-preorder-2',
      },
    },
  },
  {
    _type: 'preOrder',
    id: 'po3',
    name: 'Ferrari SF90 XX Stradale',
    slug: { _type: 'slug', current: 'ferrari-sf90-xx-stradale' },
    expectedPrice: 'From LKR 195,000,000',
    expectedArrival: 'Q3 2025',
    slotsAvailable: 1,
    specifications: ['V8 Hybrid', '1,016 HP', 'Active aero package'],
    deliveryDuration: {
      title: 'Delivery Duration',
      body: '12-16 weeks from order confirmation. Limited production model.',
      items: [
        'Standard delivery: 12-14 weeks',
        'Custom specifications: 14-16 weeks',
      ],
    },
    warrantyCoverage: {
      title: 'Warranty Coverage',
      body: '3 years unlimited mileage',
      items: [
        'Engine and transmission',
        'Hybrid system',
        'Electrical systems',
        'Carbon fiber components',
        'Manufacturing defects',
        '24/7 concierge service',
        'Free service for first 20,000 km',
        'Track day support',
      ],
    },
    personalLCImport: {
      title: 'Personal LC Import',
      body: 'Personal Letter of Credit (LC) allows individuals to import vehicles for personal use with simplified documentation.',
      items: [
        'Simplified import process for personal use',
        'Lower documentation requirements',
        'Faster processing time (2-3 weeks)',
        'Direct ownership transfer',
        'Suitable for first-time importers',
      ],
    },
    nonPersonalLCImport: {
      title: 'Non-Personal LC Import',
      body: 'Non-Personal LC is ideal for businesses, companies, or commercial vehicle imports with comprehensive documentation.',
      items: [
        'Suitable for commercial/business use',
        'Tax benefits for registered businesses',
        'Bulk import options available',
        'Corporate financing options',
        'Dedicated account manager support',
      ],
    },
    image: {
      _type: 'image',
      asset: {
        _type: 'reference',
        _ref: 'image-preorder-3',
      },
    },
  },
]

// Features
const features = [
  {
    _type: 'feature',
    title: 'Trusted Dealers',
    description:
      'Vetted partners with proven track records ensuring authentic, quality vehicles every time.',
    icon: 'Shield',
    order: 0,
  },
  {
    _type: 'feature',
    title: 'Premium Imports',
    description:
      'Direct access to exclusive international models and limited editions from around the globe.',
    icon: 'Award',
    order: 1,
  },
  {
    _type: 'feature',
    title: 'Transparent Pricing',
    description:
      'No hidden fees, no surprises. Competitive prices with complete cost breakdown upfront.',
    icon: 'DollarSign',
    order: 2,
  },
  {
    _type: 'feature',
    title: 'After-Sales Support',
    description:
      'Dedicated support team available for maintenance, queries, and assistance post-purchase.',
    icon: 'Headphones',
    order: 3,
  },
]

async function migrate() {
  console.log('Starting migration to Sanity...\n')

  try {
    // Migrate site settings
    console.log('Migrating site settings...')
    try {
      await client.createOrReplace({
        ...siteSettings,
        _id: 'siteSettings-1',
      })
      console.log('✓ Migrated site settings')
    } catch (error: any) {
      console.error('✗ Failed to migrate site settings:', error.message)
    }

    // Migrate hero section settings
    console.log('\nMigrating hero section settings...')
    try {
      await client.createOrReplace({
        ...heroSection,
        _id: 'heroSection-1',
      })
      console.log('✓ Migrated hero section settings')
    } catch (error: any) {
      console.error('✗ Failed to migrate hero section settings:', error.message)
    }

    // Migrate hero images
    console.log('\nMigrating hero images...')
    for (const image of heroImages) {
      try {
        await client.createOrReplace({
          ...image,
          _id: `heroImage-${image.order}`,
        })
        console.log(`✓ Migrated hero image #${image.order}`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate hero image #${image.order}:`, error.message)
      }
    }

    // Migrate vehicles
    console.log('\nMigrating vehicles...')
    for (const vehicle of vehicles) {
      try {
        await client.createOrReplace({
          ...vehicle,
          _id: `vehicle-${vehicle.id}`,
        })
        console.log(`✓ Migrated vehicle: ${vehicle.name}`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate vehicle ${vehicle.name}:`, error.message)
      }
    }

    // Migrate testimonials
    console.log('\nMigrating testimonials...')
    for (const testimonial of testimonials) {
      try {
        await client.createOrReplace({
          ...testimonial,
          _id: `testimonial-${testimonial.order}`,
        })
        console.log(`✓ Migrated testimonial: ${testimonial.name}`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate testimonial ${testimonial.name}:`, error.message)
      }
    }

    // Migrate FAQs
    console.log('\nMigrating FAQs...')
    for (const faq of faqs) {
      try {
        await client.createOrReplace({
          ...faq,
          _id: `faq-${faq.order}`,
        })
        console.log(`✓ Migrated FAQ: ${faq.question.substring(0, 50)}...`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate FAQ:`, error.message)
      }
    }

    // Migrate pre-orders
    console.log('\nMigrating pre-orders...')
    for (const preOrder of preOrders) {
      try {
        await client.createOrReplace({
          ...preOrder,
          _id: `preOrder-${preOrder.id}`,
        })
        console.log(`✓ Migrated pre-order: ${preOrder.name}`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate pre-order ${preOrder.name}:`, error.message)
      }
    }

    // Migrate features
    console.log('\nMigrating features...')
    for (const feature of features) {
      try {
        await client.createOrReplace({
          ...feature,
          _id: `feature-${feature.order}`,
        })
        console.log(`✓ Migrated feature: ${feature.title}`)
      } catch (error: any) {
        console.error(`✗ Failed to migrate feature ${feature.title}:`, error.message)
      }
    }

    console.log('\n✅ Migration completed!')
    console.log('\n⚠️  Note: Images need to be uploaded manually through Sanity Studio.')
    console.log('   1. Open Sanity Studio: http://localhost:3000/studio')
    console.log('   2. Navigate to each content type')
    console.log('   3. Upload images for each document')
    console.log('   4. Images will be automatically optimized and converted to WebP')
  } catch (error: any) {
    console.error('Migration failed:', error)
    process.exit(1)
  }
}

migrate()

