#!/usr/bin/env node

/**
 * Setup script to create .env.local file
 * Run: node scripts/setup-env.js
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

const envPath = path.join(process.cwd(), '.env.local')
const examplePath = path.join(process.cwd(), '.env.local.example')

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve))
}

async function setup() {
  console.log('\n🚀 Sanity CMS Environment Variables Setup\n')
  console.log('This script will help you create a .env.local file.\n')

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env.local already exists. Overwrite? (y/N): ')
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Cancelled.')
      rl.close()
      return
    }
  }

  console.log('\n📋 Please provide the following information:\n')
  console.log('You can get these from: https://sanity.io/manage\n')

  const projectId = await question('1. Sanity Project ID: ')
  const dataset = await question('2. Dataset name (default: production): ') || 'production'
  const apiVersion = await question('3. API Version (default: 2024-01-01): ') || '2024-01-01'
  const writeToken = await question('4. Write Token (for migration, optional for now): ') || ''

  const envContent = `# Sanity CMS Configuration
# Generated by setup script

# Required: Your Sanity Project ID
NEXT_PUBLIC_SANITY_PROJECT_ID=${projectId}

# Required: Your Sanity Dataset name
NEXT_PUBLIC_SANITY_DATASET=${dataset}

# Optional: API Version
NEXT_PUBLIC_SANITY_API_VERSION=${apiVersion}

# Optional: Read token for public read access
SANITY_API_READ_TOKEN=

# Required for migration script: Write token with Editor permissions
SANITY_API_WRITE_TOKEN=${writeToken}
`

  try {
    fs.writeFileSync(envPath, envContent)
    console.log('\n✅ Success! Created .env.local file\n')
    console.log('📝 Next steps:')
    console.log('   1. Restart your dev server: npm run dev')
    console.log('   2. Open Sanity Studio: http://localhost:3000/studio')
    if (!writeToken) {
      console.log('   3. Add SANITY_API_WRITE_TOKEN to .env.local to run migration script')
    }
    console.log('')
  } catch (error) {
    console.error('\n❌ Error creating .env.local:', error.message)
  }

  rl.close()
}

setup()

